tools:
    php_code_sniffer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
    php_cs_fixer: true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled: true
    php_changetracking: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 600

build_failure_conditions:
    # No new element rated worse than a D exists
    - 'elements.rating(<= D).new.exists'
    # No new major or higher severity issues exist
    # - 'issues.severity(>= MAJOR).new.exists'
    # No critical issues exist
    # - 'issues.severity(>= CRITICAL).exists'
    # Code Coverage has not decreased from previous inspection by more than 5%
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'
