#!/bin/sh

set -e

COWFILE_DEFAULT=/tmp/cow-file-${USER}

GROUPHOME=/group/teaching/cs/webuml
UMLPROGRAM=${GROUPHOME}/linux-2006-01-26 
UMLIMAGE_DEFAULT=${GROUPHOME}/uml-rootfs-2006-02-02


if [ x$1 = x"-h" ] || [ x$1 = x"--help" ]; then
    echo "Usage: $0 [ COWFILE ] [ UMLIMAGE ]"
    echo "   COWFILE defaults to $COWFILE_DEFAULT"
    echo "   UMLIMAGE defaults to $UMLIMAGE_DEFAULT"
    exit 1
fi

if [ -z $1 ]; then
    COWFILE=$COWFILE_DEFAULT
else
    COWFILE=$1
fi

if [ -z $2 ]; then
    UMLIMAGE=$UMLIMAGE_DEFAULT
else
    UMLIMAGE=$2
fi

echo "Using the COW file: ${COWFILE} and UML image ${UMLIMAGE}"

HOSTNAME=`hostname --fqdn`

if [ x$HOSTNAME = x"tarn.inf.ed.ac.uk" ] || [ x$HOSTNAME = x"hadrian.inf.ed.ac.uk" ]; then
	echo "You shouldn't be running the UML machine on any of the gateway machines."
	exit 1
fi

if [ x$HOSTNAME = x"beefy.inf.ed.ac.uk" ] || [ x$HOSTNAME = x"hefty.inf.ed.ac.uk" ]; then
	echo "You shouldn't be running the UML machine on a compute server."
	exit 1
fi


if [ -O $COWFILE ]; then # i.e. if the COW file exists and is owned by the current user...
	ROOTFSPARAM="ubd0=$COWFILE"
	chmod go-rw $COWFILE # in case was copied here with global read permissions
elif [ -a $COWFILE ]; then # i.e. the COW file exists
	echo "The COW file $COWFILE exists, but seems to be owned by a different user."
	exit 1
else
	ROOTFSPARAM="ubd0=$COWFILE,$UMLIMAGE"
fi

if dirname $COWFILE | xargs df | egrep nfs; then
	echo "It looks as if you're trying to use a COW file on an NFS parition"
	echo "e.g. your DICE home directory.  You should only use COW files"
	echo "when they're in local directories (e.g. /tmp or /var/tmp)"
	exit 1
fi

if netstat -an | egrep '^tcp +[0-9]+ +[0-9]+ +[:\.0-9]+:2200 '; then
	echo "It looks as if something on your computer is using port 2200."
	echo "It's a bad idea to start up UML in that case, since binding"
	echo "to that port will fail and you won't be able to log in with"
	echo "ssh."
	exit 1
fi

umask 0077

nice $UMLPROGRAM \
    $ROOTFSPARAM \
    eth0=slirp,,${GROUPHOME}/slirp-wrapper \
    mem=256M

echo "==========----------- "
echo "| If you've finished using UML on this computer today, "
echo "| remember to copy your COW file to your DICE space before "
echo "| leaving, e.g. with: "
echo "|     cp -i --sparse=always $COWFILE ~"
echo "|======-------------- "
