#!/bin/bash

# Parsing

FROMDATE=$1
LORDFROMDATE=$2
TODATE=$3
RET=0
# $4 is extra flags to pass through
# echo "updatedaterange from $1/$2 to $3"

# Run parsers to convert various HTML into XML
cd ~/parlparse/pyscraper
# We do these on separate lines, so if one fails, others still run
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse debates || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse wrans || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse westminhall || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse wms || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse lords || RET=1
./lazyrunall.py $4 --quietc --from=$FROMDATE --to=$TODATE parse ni || RET=1

# Public Bill Committee transcripts
cd ~/parlparse/pyscraper/standing
./parse.py $4

# Scottish Parliament - must be this order
cd ~/parlparse/pyscraper/sp
./parse-written-answers.py --quiet $4
./parse.py --quiet $4
./parse-question-mentions.py --modified $4
./parse-motions.py $4

# Return error code
exit $RET
