#! /usr/bin/perl -w
# compactsearchdb. Compacts the Xapian search database
#
# $Id: compactsearchdb,v 1.6 2009-10-28 10:33:00 matthew Exp $

use strict;

use FindBin;
use File::Copy;
use File::Path;
use lib "$FindBin::Bin/../commonlib/perllib";

use mySociety::Config;
mySociety::Config::set_file("$FindBin::Bin/../conf/general");

my $xapian = mySociety::Config::get('XAPIANDB');

rmtree("$xapian-compacted"); # This should never be present anyway.
rmtree("$xapian-previous"); # Remove old backup.
system("xapian-compact $xapian/ $xapian-compacted/ >/dev/null");
rename $xapian, "$xapian-previous";
rename "$xapian-compacted", $xapian;
copy "$xapian-previous/twfy-lastupdated", "$xapian/twfy-lastupdated";

