#! /usr/bin/perl -w
# compactsearchdb. Compacts the Xapian search database
#
# $Id: compactsearchdb,v 1.3 2008-03-09 11:58:51 matthew Exp $

use strict;

use FindBin;
use File::Path;
use lib "$FindBin::Bin/../../perllib";

use mySociety::Config;
mySociety::Config::set_file("$FindBin::Bin/../conf/general");

my $xapian = mySociety::Config::get('XAPIANDB');

chdir $xapian . '/../';
rmtree('searchdb-compacted');
system('xapian-compact searchdb/ searchdb-compacted/ >/dev/null');
rmtree('searchdb-previous');
rename 'searchdb', 'searchdb-previous';
rename 'searchdb-compacted', 'searchdb';

