#! /usr/bin/perl -w
# Jobs that need running daily, that aren't with urgency dependent on new stuff
# from Hansard
#
# $Id: dailyupdate,v 1.4 2008-12-09 16:52:47 angie Exp $

use strict;

use FindBin;
my $root;
BEGIN {
    $root = "$FindBin::Bin/..";
}
use lib "$root/commonlib/perllib";
my $cron_log = "$root/../applogs/cron.log";

use mySociety::Config;
mySociety::Config::set_file("$root/conf/general");

my $staging = mySociety::Config::get('DEVSITE');
my $pwmembers = mySociety::Config::get('PWMEMBERS');

# Update MP info from Public Whip, FaxYourMP and other places
unless ($staging) {
    chdir $pwmembers;
    system 'git pull -q';
}
chdir $FindBin::Bin;
system './mpinfoin.pl';

# Update register of interests
system "TQDM_DISABLE=1 ./personinfo upload-all-regmem >> $cron_log";

# Update APPG memberships
system "TQDM_DISABLE=1 ./personinfo upload-all-regmem >> $cron_log";

# Update EDM and open letter signatures
system "TQDM_DISABLE=1 ./personinfo load-statement-signatures >> $cron_log";

# update policies information
system "./votes2db load-policies >> $cron_log";

# upload party alignment (rebellions)
system "./votes2db load-voting-alignment >> $cron_log";

# Add yesterdays optins to mailchimp
system "poetry run contact-io upload-yesterday >> $cron_log";