#!/usr/bin/perl 

use strict;
use DBI;
use FindBin;
use lib "$FindBin::Bin/../../perllib";
use mySociety::Config;
mySociety::Config::set_file('../conf/general');

my $dsn = 'DBI:mysql:database=' . mySociety::Config::get('DB_NAME'). ':host=' . mySociety::Config::get('DB_HOST');
my $dbh = DBI->connect($dsn, mySociety::Config::get('DB_USER'), mySociety::Config::get('DB_PASSWORD'), { RaiseError => 1, PrintError => 0 });
my $q = $dbh->prepare('update alerts set deleted=1 where email=?');

while (<>) {
	chomp;
	my $r = $q->execute($_);
	print "$r\n";
}
