#!/bin/bash
set -e


if [[ 97 <  ` df -k /usr | perl -e '$/=undef; $a= <STDIN>; $a=~ m#(\d+)\%#; print $1'` ]] ; then
	echo "  Backup cancelled due to lack of space on cake!";
	exit 1;
fi

#echo "wouldn't die"
#exit 0;


# Dumps database for backups
/usr/local/bin/mysqldump --skip-lock-tables fawkes | bzip2 -c > ~/backup/twfy-all-including-sensitive-data-`date +%F`.sql.bz2

# As sams suggests, keep whole of last month, and first of month before then

cd ~/backup

# Move first of month
touch dummy-01.sql.bz2
mv *-01.sql.bz2 firsts
rm firsts/dummy-01.sql.bz2
#echo firsts
#ls -1 firsts

# Delete all except 20
ls -1 twfy-all-including-sensitive-data-*.sql.bz2 | fgrep -v "`ls -1 twfy-all-including-sensitive-data-*.sql.bz2 | sort -n | tail -n 20`" | while read X
do
	#echo "Deleting old backup $X"
	rm $X
done

