#!/bin/bash
# For a fresh install get a basic set of data in

echo 'Cloning parlparse'
git clone https://github.com/mysociety/parlparse data/parlparse --depth 1

# See http://parser.theyworkforyou.com/hansard.html for details on download specific ranges
echo 'Downloading minimal data'
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedxml/debates/debates2022-01* data/pwdata
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedjson data/pwdata
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/people.json data/pwdata
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedxml/regme* data/pwdata
echo 'Downloading minimal Senedd'
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedxml/senedd/en/senedd2022-01* data/pwdata
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedxml/senedd/cy/senedd2022-01* data/pwdata

echo 'Downloading minimal Scottish Parliament'
rsync -az --progress --exclude '.svn' --exclude 'tmp/' --relative data.theyworkforyou.com::parldata/scrapedxml/sp-new/meeting-of-the-parliament/2022-01* data/pwdata

echo 'Load people into database'
scripts/load-people

echo 'Load regmem into database'
scripts/personinfo upload-all-regmem
scripts/personinfo upload-enhanced-2024-regmem

echo 'Load policies and votes from twfy-votes'
scripts/votes2db load-policies 
scripts/votes2db load-voting-alignment 
scripts/votes2db load-dev-votes

echo 'Load Jan 2022 debates and divisions'
scripts/xml2db.pl --debates --wales --scotland --all

echo 'Generate search index'
search/index.pl all
echo 'Quick setup completed'
