name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.2", "8.3", "8.4"]

    services:
      mariadb:
        image: mariadb:11.8
        ports:
          - 3306:3306
        command: '--sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: '1'
          MARIADB_USER: twfy
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: twfy
          MARIADB_AUTO_UPGRADE: '1'
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-start-period=60s
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: bitnamisecure/redis
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: password
        options: >-
          --health-cmd="redis-cli -a password ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis-sentinel:
        image: bitnamisecure/redis-sentinel
        env:
          REDIS_MASTER_HOST: redis
          REDIS_MASTER_SET: mymaster
          REDIS_MASTER_PASSWORD: password
          REDIS_SENTINEL_QUORUM: 1
          ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 26379:26379
        options: >-
          --health-cmd="redis-cli -p 26379 ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: niden/actions-memcached@v8

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: memcached

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(php composer.phar config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-composer-

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping \
            -h 127.0.0.1 \
            -u twfy \
            -ppassword \
            --silent; do
            sleep 1
          done

      - name: Set up database and code
        run: |
          mysql \
            -h 127.0.0.1 \
            -u twfy \
            -ppassword \
            twfy < db/schema.sql

          php composer.phar install --no-interaction

      - name: Run tests
        env:
          TWFY_TEST_DB_HOST: "127.0.0.1"
          TWFY_TEST_DB_USER: "twfy"
          TWFY_TEST_DB_PASS: "password"
          TWFY_TEST_DB_NAME: "twfy"
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --exclude-group xapian