name: Check translations are present

on:
  pull_request:

jobs:
  check_translation:

      runs-on: ubuntu-latest

      steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: '0'

      - name: setup
        shell: bash
        run: |
          sudo apt-get install -y gettext
          sudo locale-gen en_CA.UTF-8

      - name: Check translation
        id: check_translation
        shell: bash
        run: |

          scripts/generate-translations --test